"""Review TSV and SQL writers for stable-ID decisions."""

from __future__ import annotations

import csv
from pathlib import Path
from typing import Optional

from .config import StableIdEventConfig
from .models import Decision, PK_BY_TYPE, TABLE_BY_TYPE


def sql_string(value: Optional[str]) -> str:
    if value is None:
        return "NULL"
    return "'" + value.replace("\\", "\\\\").replace("'", "''") + "'"


def sql_identifier(value: str) -> str:
    return "`" + value.replace("`", "``") + "`"


def sql_number(value: float | int) -> str:
    if isinstance(value, int):
        return str(value)
    if value.is_integer():
        return str(int(value))
    return repr(value)


def write_values_insert(
    handle,
    table_name: str,
    columns: list[str],
    rows: list[list[str]],
    batch_size: int,
) -> None:
    if not rows:
        return
    column_text = ", ".join(columns)
    for start in range(0, len(rows), batch_size):
        batch = rows[start : start + batch_size]
        handle.write(f"INSERT INTO {table_name} ({column_text}) VALUES\n")
        handle.write(",\n".join("  (" + ", ".join(row) + ")" for row in batch))
        handle.write(";\n\n")


def decision_rows(decisions: list[Decision]) -> list[list[str]]:
    return [
        [
            sql_string(decision.feature_type),
            sql_string(decision.action),
            sql_string(decision.current_stable_id),
            str(decision.current_version),
            sql_string(decision.old_stable_id),
            str(decision.old_version),
            sql_string(decision.new_stable_id),
            str(decision.new_version),
            str(decision.mapping_session_id),
            sql_number(decision.score),
            sql_string(decision.reason[:255]),
        ]
        for decision in decisions
    ]


def write_sql(
    decisions: list[Decision],
    path: str | Path,
    config: StableIdEventConfig,
) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    feature_order = ["gene", "transcript"]
    if config.include_translations:
        feature_order.append("translation")

    with path.open("w") as handle:
        handle.write("-- Generated by stable_id_mapping.\n")
        handle.write("-- Review before running against a core database.\n\n")
        if config.db_name:
            handle.write(f"USE {sql_identifier(config.db_name)};\n\n")

        if not config.dry_run:
            for table in ["gene", "transcript", "stable_id_event"]:
                handle.write(
                    f"CREATE TABLE {config.backup_prefix}_{table} AS SELECT * FROM {table};\n"
                )
            if config.include_translations:
                handle.write(
                    f"CREATE TABLE {config.backup_prefix}_translation AS SELECT * FROM translation;\n"
                )
            handle.write("\n")

        handle.write("START TRANSACTION;\n\n")

        if config.dry_run:
            decision_table = "tmp_stable_id_mapper_decisions"
            handle.write(
                f"CREATE TEMPORARY TABLE {decision_table} (\n"
                "  type VARCHAR(32) NOT NULL,\n"
                "  action VARCHAR(32) NOT NULL,\n"
                "  current_stable_id VARCHAR(128) NULL,\n"
                "  current_version INT NOT NULL,\n"
                "  old_stable_id VARCHAR(128) NULL,\n"
                "  old_version INT NOT NULL,\n"
                "  new_stable_id VARCHAR(128) NULL,\n"
                "  new_version INT NOT NULL,\n"
                "  mapping_session_id INT NOT NULL,\n"
                "  score DOUBLE NOT NULL,\n"
                "  reason VARCHAR(255) NOT NULL\n"
                ");\n\n"
            )
            write_values_insert(
                handle,
                decision_table,
                [
                    "type",
                    "action",
                    "current_stable_id",
                    "current_version",
                    "old_stable_id",
                    "old_version",
                    "new_stable_id",
                    "new_version",
                    "mapping_session_id",
                    "score",
                    "reason",
                ],
                decision_rows(decisions),
                config.batch_size,
            )
            handle.write(
                f"SELECT type, action, COUNT(*) AS decisions\n"
                f"FROM {decision_table}\n"
                "GROUP BY type, action\n"
                "ORDER BY type, action;\n\n"
            )

        if config.replace_events_for_session and not config.dry_run:
            handle.write(
                "DELETE FROM stable_id_event "
                f"WHERE mapping_session_id = {config.mapping_session_id};\n\n"
            )

        for feature_type in feature_order:
            updates = [
                decision
                for decision in decisions
                if decision.feature_type == feature_type
                and decision.current_stable_id
                and decision.new_stable_id
            ]
            if not updates:
                continue

            table_name = TABLE_BY_TYPE[feature_type]
            pk_col = PK_BY_TYPE[feature_type]
            update_table = f"tmp_stable_id_mapper_{feature_type}_update"
            pk_table = f"tmp_stable_id_mapper_{feature_type}_pk"

            handle.write(
                f"CREATE TEMPORARY TABLE {update_table} (\n"
                "  current_stable_id VARCHAR(128) NOT NULL,\n"
                "  new_stable_id VARCHAR(128) NOT NULL,\n"
                "  new_version INT NOT NULL,\n"
                "  old_stable_id VARCHAR(128) NULL,\n"
                "  old_version INT NOT NULL,\n"
                "  score DOUBLE NOT NULL,\n"
                "  action VARCHAR(32) NOT NULL,\n"
                "  reason VARCHAR(255) NOT NULL,\n"
                "  PRIMARY KEY (current_stable_id)\n"
                ");\n\n"
            )
            update_rows = [
                [
                    sql_string(decision.current_stable_id),
                    sql_string(decision.new_stable_id),
                    str(decision.new_version),
                    sql_string(decision.old_stable_id),
                    str(decision.old_version),
                    sql_number(decision.score),
                    sql_string(decision.action),
                    sql_string(decision.reason[:255]),
                ]
                for decision in updates
            ]
            write_values_insert(
                handle,
                update_table,
                [
                    "current_stable_id",
                    "new_stable_id",
                    "new_version",
                    "old_stable_id",
                    "old_version",
                    "score",
                    "action",
                    "reason",
                ],
                update_rows,
                config.batch_size,
            )
            handle.write(
                f"CREATE TEMPORARY TABLE {pk_table} AS\n"
                f"SELECT f.{pk_col}, u.*\n"
                f"FROM {table_name} f\n"
                f"JOIN {update_table} u ON f.stable_id = u.current_stable_id;\n\n"
            )
            handle.write(
                f"SELECT '{feature_type}' AS type,\n"
                f"       (SELECT COUNT(*) FROM {update_table}) AS staged_count,\n"
                f"       (SELECT COUNT(*) FROM {pk_table}) AS matched_count;\n\n"
            )
            handle.write(
                f"SELECT '{feature_type}' AS type, u.current_stable_id, u.new_stable_id, "
                "u.action, u.reason\n"
                f"FROM {update_table} u\n"
                f"LEFT JOIN {pk_table} p ON p.current_stable_id = u.current_stable_id\n"
                "WHERE p.current_stable_id IS NULL\n"
                "LIMIT 20;\n\n"
            )
            handle.write(
                f"SELECT '{feature_type}' AS type, current_stable_id, COUNT(*) AS db_matches\n"
                f"FROM {pk_table}\n"
                "GROUP BY current_stable_id\n"
                "HAVING COUNT(*) > 1\n"
                "LIMIT 20;\n\n"
            )

            if config.dry_run:
                continue

            handle.write(
                f"UPDATE {table_name} f\n"
                f"JOIN {pk_table} p ON f.{pk_col} = p.{pk_col}\n"
                f"SET f.stable_id = CONCAT('__tmp_{feature_type}_', f.{pk_col}),\n"
                "    f.version = 0;\n\n"
            )
            handle.write(
                f"UPDATE {table_name} f\n"
                f"JOIN {pk_table} p ON f.{pk_col} = p.{pk_col}\n"
                "SET f.stable_id = p.new_stable_id,\n"
                "    f.version = p.new_version;\n\n"
            )

        if config.dry_run:
            handle.write("ROLLBACK;\n")
            return

        event_rows = [
            [
                sql_string(decision.old_stable_id),
                str(decision.old_version),
                sql_string(decision.new_stable_id),
                str(decision.new_version),
                str(decision.mapping_session_id),
                sql_string(decision.feature_type),
                sql_number(decision.score),
            ]
            for decision in decisions
        ]
        write_values_insert(
            handle,
            "stable_id_event",
            [
                "old_stable_id",
                "old_version",
                "new_stable_id",
                "new_version",
                "mapping_session_id",
                "type",
                "score",
            ],
            event_rows,
            config.batch_size,
        )
        handle.write("COMMIT;\n")


def write_tsv(decisions: list[Decision], path: str | Path) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as handle:
        writer = csv.writer(handle, delimiter="\t", lineterminator="\n")
        writer.writerow(
            [
                "type",
                "action",
                "current_stable_id",
                "current_version",
                "old_stable_id",
                "old_version",
                "new_stable_id",
                "new_version",
                "mapping_session_id",
                "score",
                "reason",
            ]
        )
        for decision in decisions:
            writer.writerow(
                [
                    decision.feature_type,
                    decision.action,
                    decision.current_stable_id or "",
                    decision.current_version,
                    decision.old_stable_id or "",
                    decision.old_version,
                    decision.new_stable_id or "",
                    decision.new_version,
                    decision.mapping_session_id,
                    decision.score,
                    decision.reason,
                ]
            )

